### ISSUE TITLE
Error: bootstrap_servers was not set

### ISSUE THREAD

**Issue by wuestkamp** [Mongey/terraform-provider-confluent-cloud#13]
When trying to execute the example TF code from scratch, I'm getting:

```
Error: bootstrap_servers was not set

  on main.tf line 37, in provider "kafka":
  37: provider "kafka" {
```

This is because the Kafka provider needs bootstrap_servers to work, though these have not been created by the other resources.

Is there a way to "delay" the execution of the kafka provider?

**Comment by Mongey** [comment]
Not really related to this provider, except for the readme, https://github.com/Mongey/terraform-provider-kafka/issues/95, is the issue for tracking this over in `terraform-provider-kafka`. Something related to this must have changed with 0.12. I'm pretty sure it worked before then.
