### ISSUE TITLE
verson 0.0.1 on windows/linux has a mixup between "confluentcloud" and "confluent-cloud"

### ISSUE THREAD

**Issue by aabrams** [Mongey/terraform-provider-confluent-cloud#14]
adam@DESKTOP-MNAR8U3:/mnt/c/Users/adam_a/terraform$ ./terraform init

Initializing the backend...

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.confluent-cloud: version = "~> 0.0"
* provider.google: version = "~> 3.8"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
adam@DESKTOP-MNAR8U3:/mnt/c/Users/adam_a/terraform$ ./terraform plan

Error: Error in function call

  on demo.tf line 2, in provider "google":
   2:   credentials = file("axonite-dev-11ff7f13be93.json")

Call to function "file" failed: no file exists at
axonite-dev-11ff7f13be93.json.

Error: Invalid resource type

  on demo.tf line 9, in resource "confluent-cloud_environment" "test":
   9: resource "confluent-cloud_environment" "test" {

The provider provider.confluent-cloud does not support resource type
"confluent-cloud_environment".

Error: Invalid resource type

  on demo.tf line 13, in resource "confluent-cloud_kafka_cluster" "test":
  13: resource "confluent-cloud_kafka_cluster" "test" {

The provider provider.confluent-cloud does not support resource type
"confluent-cloud_kafka_cluster".

**Comment by aabrams** [comment]
Using Terraform 0.12.20, BTW. Perhaps the provider works better on version 0.11?

**Comment by Mongey** [comment]
whoops🤦‍♂  this is a problem with the release scripts.
can you rename the binary to `terraform-provider_confluentcloud` and use `provider "confluentcloud"` and `resource "confluentcloud_*"` in your terraform file. I think that should fix it. I'll update the release scripts to rename the binary.

**Comment by aabrams** [comment]
Changing the filename fixed it!
