### ISSUE TITLE
Pre-built releases

### ISSUE THREAD

**Issue by Nevon** [Mongey/terraform-provider-confluent-cloud#7]
The README links to the releases page, and it looks like there some builds happening, but no binaries available from there.

Would it be possible to create a release with pre-built binaries? I don't have the Go toolchain set up myself, so having pre-built binaries would be great.

**Comment by wuestkamp** [comment]
Second that

**Comment by Mongey** [comment]
You can now grab binaries over on the release page:
https://github.com/Mongey/terraform-provider-confluent-cloud/releases

**Comment by Nevon** [comment]
Thanks a bunch!
