### ISSUE TITLE
Internal validation of the provider failed

### ISSUE THREAD

**Issue by cedricarnoult** [Mongey/terraform-provider-confluent-cloud#9]
First of all, this is a very interesting plugin. I've been looking for this kind of thing for a while.

I'm new in confluent world and I'm trying to create a cluster with the code:

```
terraform {
  backend "gcs" {
  }
}

provider "confluentcloud" {
  version = "0.0.1"
}

resource "confluentcloud_environment" "environment" {
  name = "Default"
}

resource "confluentcloud_kafka_cluster" "kafka_cluster" {
  name             = "my-cluster"
  environment_id   = confluentcloud_environment.environment.id
  service_provider = "gcp"
  region           = "europe-west1"
  availability     = "single-zone"
}

resource "confluentcloud_api_key" "provider_test" {
  cluster_id     = confluentcloud_kafka_cluster.kafka_cluster.id
  environment_id = confluentcloud_environment.environment.id
}
```

I have build the plugin, placed in appropriate folder (it's found in the log) and I have setup the 2 environment variables. I'm using version 0.0.1.

The error message I have is:
> Error: Internal validation of the provider failed! This is always a bug
> with the provider itself, and not a user issue. Please report
> this bug:
> 
> 1 error occurred:
> 	* resource confluentcloud_environment: All fields are ForceNew or Computed w/out Optional, Update is superfluous
> 

Looking at the go code, resource_environment.go has only the parameter 'name' which I am providing ...

What am I missing ?

**Comment by wuestkamp** [comment]
I'm getting the same error.
